
/**
 * AUTO-GENERATED CONFIG - DO NOT EDIT MANUALLY
 * Generated by scripts/generate_functions_config.ts
 * 
 * This file lists all available Supabase Edge Functions detected in the codebase.
 * It is used by the Master Control Panel to generate the UI.
 */

export interface EdgeFunctionConfig {
  name: string;
  category: 'core' | 'agent' | 'integration' | 'utility' | 'webhook';
  description: string;
  requiredSecrets: string[];
  isUsedInApp: boolean;
}

export const SUPABASE_EDGE_FUNCTIONS: EdgeFunctionConfig[] = [
  {
    name: "agent-analyst",
    category: "agent",
    description: "Auto-detected function: agent-analyst",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "agent-orchestrator",
    category: "agent",
    description: "Auto-detected function: agent-orchestrator",
    requiredSecrets: ["STRIPE_SECRET_KEY","STRIPE_WEBHOOK_SECRET","GEMINI_API_KEY","GOOGLE_API_KEY","LOVABLE_API_KEY","LANGSMITH_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "ai-ceo-master",
    category: "agent",
    description: "Auto-detected function: ai-ceo-master",
    requiredSecrets: ["GOOGLE_API_KEY","GEMINI_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","LANGCHAIN_PROJECT"],
    isUsedInApp: false
  },
  {
    name: "ai-config-status",
    category: "agent",
    description: "Auto-detected function: ai-config-status",
    requiredSecrets: ["GEMINI_API_KEY","GOOGLE_API_KEY","ANTHROPIC_API_KEY","OPENAI_API_KEY","STRIPE_SECRET_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "ai-deploy-callback",
    category: "agent",
    description: "Auto-detected function: ai-deploy-callback",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "ai-trigger-deploy",
    category: "agent",
    description: "Auto-detected function: ai-trigger-deploy",
    requiredSecrets: ["GITHUB_TOKEN","GITHUB_REPO","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "anomaly-detector",
    category: "utility",
    description: "Auto-detected function: anomaly-detector",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "anytrack-webhook",
    category: "webhook",
    description: "Auto-detected function: anytrack-webhook",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "api-rate-limit-handler",
    category: "utility",
    description: "Auto-detected function: api-rate-limit-handler",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "auto-reassign-leads",
    category: "utility",
    description: "Auto-detected function: auto-reassign-leads",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "business-intelligence",
    category: "agent",
    description: "Auto-detected function: business-intelligence",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "calculate-health-scores",
    category: "utility",
    description: "Auto-detected function: calculate-health-scores",
    requiredSecrets: ["HUBSPOT_ACCESS_TOKEN","HUBSPOT_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "calendly-webhook",
    category: "webhook",
    description: "Auto-detected function: calendly-webhook",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "callgear-error-handler",
    category: "integration",
    description: "Auto-detected function: callgear-error-handler",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","CALLGEAR_API_KEY"],
    isUsedInApp: false
  },
  {
    name: "callgear-forensics",
    category: "integration",
    description: "Auto-detected function: callgear-forensics",
    requiredSecrets: ["CALLGEAR_API_KEY"],
    isUsedInApp: false
  },
  {
    name: "callgear-icp-router",
    category: "integration",
    description: "Auto-detected function: callgear-icp-router",
    requiredSecrets: ["CALLGEAR_API_KEY","FAILSAFE_ROUTING_PHONES","VIP_NUMBERS","BLACKLISTED_NUMBERS","VIP_ROUTING_PHONES","DEFAULT_ROUTING_PHONES","SALES_PHONES","SUPPORT_PHONES","BILLING_PHONES","OPERATOR_PHONES"],
    isUsedInApp: false
  },
  {
    name: "callgear-live-monitor",
    category: "integration",
    description: "Auto-detected function: callgear-live-monitor",
    requiredSecrets: ["CALLGEAR_API_URL","CALLGEAR_API_KEY"],
    isUsedInApp: false
  },
  {
    name: "callgear-sentinel",
    category: "integration",
    description: "Auto-detected function: callgear-sentinel",
    requiredSecrets: ["CALLGEAR_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","SUSPICIOUS_PHONE_NUMBERS","SENSITIVE_PHONE_LINES","AI_COACH_SIP_URI","SMS_ALERT_WEBHOOK_URL"],
    isUsedInApp: false
  },
  {
    name: "callgear-supervisor",
    category: "integration",
    description: "Auto-detected function: callgear-supervisor",
    requiredSecrets: ["CALLGEAR_API_KEY"],
    isUsedInApp: false
  },
  {
    name: "capi-validator",
    category: "utility",
    description: "Auto-detected function: capi-validator",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "churn-predictor",
    category: "utility",
    description: "Auto-detected function: churn-predictor",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","ANTHROPIC_API_KEY"],
    isUsedInApp: true
  },
  {
    name: "cleanup-errors",
    category: "utility",
    description: "Auto-detected function: cleanup-errors",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "cleanup-fake-contacts",
    category: "utility",
    description: "Auto-detected function: cleanup-fake-contacts",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "client-payment-integrity",
    category: "utility",
    description: "Auto-detected function: client-payment-integrity",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","STRIPE_SECRET_KEY"],
    isUsedInApp: false
  },
  {
    name: "coach-analyzer",
    category: "utility",
    description: "Auto-detected function: coach-analyzer",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "daily-report",
    category: "utility",
    description: "Auto-detected function: daily-report",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "data-quality",
    category: "core",
    description: "Auto-detected function: data-quality",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "db-inspector",
    category: "utility",
    description: "Auto-detected function: db-inspector",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "debug-env",
    category: "utility",
    description: "Auto-detected function: debug-env",
    requiredSecrets: ["GEMINI_API_KEY"],
    isUsedInApp: false
  },
  {
    name: "deep-research",
    category: "utility",
    description: "Auto-detected function: deep-research",
    requiredSecrets: ["GEMINI_API_KEY","GOOGLE_API_KEY","GOOGLE_GEMINI_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "emergency-forensics",
    category: "utility",
    description: "Auto-detected function: emergency-forensics",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "enrich-with-stripe",
    category: "integration",
    description: "Auto-detected function: enrich-with-stripe",
    requiredSecrets: ["STRIPE_SECRET_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "error-auto-resolver",
    category: "utility",
    description: "Auto-detected function: error-auto-resolver",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "error-cleanup-agent",
    category: "agent",
    description: "Auto-detected function: error-cleanup-agent",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "error-correlation-agent",
    category: "agent",
    description: "Auto-detected function: error-correlation-agent",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "error-health-monitor",
    category: "utility",
    description: "Auto-detected function: error-health-monitor",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "error-notification-agent",
    category: "agent",
    description: "Auto-detected function: error-notification-agent",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "error-pattern-analyzer",
    category: "utility",
    description: "Auto-detected function: error-pattern-analyzer",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "error-prediction-agent",
    category: "agent",
    description: "Auto-detected function: error-prediction-agent",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "error-prevention-agent",
    category: "agent",
    description: "Auto-detected function: error-prevention-agent",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","HUBSPOT_API_KEY","STRIPE_SECRET_KEY","META_ACCESS_TOKEN","FACEBOOK_ACCESS_TOKEN","CALLGEAR_API_KEY"],
    isUsedInApp: false
  },
  {
    name: "error-recovery-agent",
    category: "agent",
    description: "Auto-detected function: error-recovery-agent",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "error-retry-orchestrator",
    category: "utility",
    description: "Auto-detected function: error-retry-orchestrator",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "error-rollback-agent",
    category: "agent",
    description: "Auto-detected function: error-rollback-agent",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "error-root-cause-analyzer",
    category: "utility",
    description: "Auto-detected function: error-root-cause-analyzer",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "error-severity-classifier",
    category: "utility",
    description: "Auto-detected function: error-severity-classifier",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "error-trend-analyzer",
    category: "utility",
    description: "Auto-detected function: error-trend-analyzer",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "error-triage-agent",
    category: "agent",
    description: "Auto-detected function: error-triage-agent",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "fetch-callgear-data",
    category: "integration",
    description: "Auto-detected function: fetch-callgear-data",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","CALLGEAR_API_KEY"],
    isUsedInApp: false
  },
  {
    name: "fetch-facebook-insights",
    category: "utility",
    description: "Auto-detected function: fetch-facebook-insights",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","FB_ACCESS_TOKEN","FB_AD_ACCOUNT_ID"],
    isUsedInApp: true
  },
  {
    name: "fetch-forensic-data",
    category: "utility",
    description: "Auto-detected function: fetch-forensic-data",
    requiredSecrets: ["HUBSPOT_API_KEY","HUBSPOT_ACCESS_TOKEN"],
    isUsedInApp: true
  },
  {
    name: "fetch-hubspot-live",
    category: "integration",
    description: "Auto-detected function: fetch-hubspot-live",
    requiredSecrets: ["HUBSPOT_API_KEY"],
    isUsedInApp: true
  },
  {
    name: "generate-daily-snapshot",
    category: "utility",
    description: "Auto-detected function: generate-daily-snapshot",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "generate-embeddings",
    category: "utility",
    description: "Auto-detected function: generate-embeddings",
    requiredSecrets: ["OPENAI_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "generate-lead-replies",
    category: "utility",
    description: "Auto-detected function: generate-lead-replies",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","ANTHROPIC_API_KEY"],
    isUsedInApp: false
  },
  {
    name: "generate-lead-reply",
    category: "utility",
    description: "Auto-detected function: generate-lead-reply",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","ANTHROPIC_API_KEY"],
    isUsedInApp: false
  },
  {
    name: "health-calculator",
    category: "utility",
    description: "Auto-detected function: health-calculator",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "hubspot-analyzer",
    category: "integration",
    description: "Auto-detected function: hubspot-analyzer",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "hubspot-anytrack-webhook",
    category: "webhook",
    description: "Auto-detected function: hubspot-anytrack-webhook",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "hubspot-command-center",
    category: "integration",
    description: "Auto-detected function: hubspot-command-center",
    requiredSecrets: ["HUBSPOT_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "hubspot-error-handler",
    category: "integration",
    description: "Auto-detected function: hubspot-error-handler",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","HUBSPOT_API_KEY"],
    isUsedInApp: false
  },
  {
    name: "hubspot-live-query",
    category: "integration",
    description: "Auto-detected function: hubspot-live-query",
    requiredSecrets: ["HUBSPOT_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "hubspot-webhook",
    category: "webhook",
    description: "Auto-detected function: hubspot-webhook",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "integration-health",
    category: "utility",
    description: "Auto-detected function: integration-health",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","HUBSPOT_API_KEY","STAPE_CAPIG_API_KEY"],
    isUsedInApp: true
  },
  {
    name: "intervention-recommender",
    category: "utility",
    description: "Auto-detected function: intervention-recommender",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","ANTHROPIC_API_KEY"],
    isUsedInApp: true
  },
  {
    name: "marketing-stress-test",
    category: "utility",
    description: "Auto-detected function: marketing-stress-test",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "meta-error-handler",
    category: "integration",
    description: "Auto-detected function: meta-error-handler",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","META_ACCESS_TOKEN","FACEBOOK_ACCESS_TOKEN"],
    isUsedInApp: false
  },
  {
    name: "openai-embeddings",
    category: "agent",
    description: "Auto-detected function: openai-embeddings",
    requiredSecrets: ["OPENAI_API_KEY"],
    isUsedInApp: false
  },
  {
    name: "pipeline-monitor",
    category: "utility",
    description: "Auto-detected function: pipeline-monitor",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "proactive-insights-generator",
    category: "utility",
    description: "Auto-detected function: proactive-insights-generator",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","GEMINI_API_KEY","GOOGLE_API_KEY","LOVABLE_API_KEY"],
    isUsedInApp: true
  },
  {
    name: "process-capi-batch",
    category: "utility",
    description: "Auto-detected function: process-capi-batch",
    requiredSecrets: ["STAPE_CAPIG_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "process-knowledge",
    category: "utility",
    description: "Auto-detected function: process-knowledge",
    requiredSecrets: ["OPENAI_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "ptd-24x7-monitor",
    category: "utility",
    description: "Auto-detected function: ptd-24x7-monitor",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "ptd-agent",
    category: "agent",
    description: "Auto-detected function: ptd-agent",
    requiredSecrets: ["ANTHROPIC_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "ptd-agent-claude",
    category: "agent",
    description: "Auto-detected function: ptd-agent-claude",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "ptd-agent-gemini",
    category: "agent",
    description: "Auto-detected function: ptd-agent-gemini",
    requiredSecrets: ["OPENAI_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","LOVABLE_API_KEY","GEMINI_API_KEY","GOOGLE_API_KEY"],
    isUsedInApp: true
  },
  {
    name: "ptd-execute-action",
    category: "utility",
    description: "Auto-detected function: ptd-execute-action",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","GITHUB_TOKEN","GITHUB_OWNER","GITHUB_REPO"],
    isUsedInApp: false
  },
  {
    name: "ptd-proactive-scanner",
    category: "utility",
    description: "Auto-detected function: ptd-proactive-scanner",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "ptd-self-developer",
    category: "utility",
    description: "Auto-detected function: ptd-self-developer",
    requiredSecrets: ["ANTHROPIC_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "ptd-self-learn",
    category: "utility",
    description: "Auto-detected function: ptd-self-learn",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "ptd-ultimate-intelligence",
    category: "agent",
    description: "Auto-detected function: ptd-ultimate-intelligence",
    requiredSecrets: ["ANTHROPIC_API_KEY","GEMINI_API_KEY","GOOGLE_API_KEY","GOOGLE_GEMINI_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","LANGCHAIN_PROJECT"],
    isUsedInApp: false
  },
  {
    name: "ptd-watcher",
    category: "utility",
    description: "Auto-detected function: ptd-watcher",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","GEMINI_API_KEY"],
    isUsedInApp: true
  },
  {
    name: "purge-sync-errors",
    category: "utility",
    description: "Auto-detected function: purge-sync-errors",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "reassign-owner",
    category: "utility",
    description: "Auto-detected function: reassign-owner",
    requiredSecrets: ["HUBSPOT_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "run-migration",
    category: "utility",
    description: "Auto-detected function: run-migration",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "sales-aggression",
    category: "utility",
    description: "Auto-detected function: sales-aggression",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "send-to-stape-capi",
    category: "utility",
    description: "Auto-detected function: send-to-stape-capi",
    requiredSecrets: ["STAPE_CAPIG_API_KEY"],
    isUsedInApp: true
  },
  {
    name: "smart-agent",
    category: "agent",
    description: "Auto-detected function: smart-agent",
    requiredSecrets: ["GEMINI_API_KEY","GOOGLE_API_KEY","LOVABLE_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "smart-coach-analytics",
    category: "utility",
    description: "Auto-detected function: smart-coach-analytics",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "stripe-account-details",
    category: "integration",
    description: "Auto-detected function: stripe-account-details",
    requiredSecrets: ["STRIPE_SECRET_KEY"],
    isUsedInApp: false
  },
  {
    name: "stripe-checkout",
    category: "integration",
    description: "Auto-detected function: stripe-checkout",
    requiredSecrets: ["STRIPE_SECRET_KEY"],
    isUsedInApp: false
  },
  {
    name: "stripe-connect",
    category: "integration",
    description: "Auto-detected function: stripe-connect",
    requiredSecrets: ["STRIPE_SECRET_KEY"],
    isUsedInApp: false
  },
  {
    name: "stripe-dashboard-data",
    category: "integration",
    description: "Auto-detected function: stripe-dashboard-data",
    requiredSecrets: ["STRIPE_SECRET_KEY","LANGSMITH_API_KEY"],
    isUsedInApp: true
  },
  {
    name: "stripe-deep-agent",
    category: "agent",
    description: "Auto-detected function: stripe-deep-agent",
    requiredSecrets: ["STRIPE_SECRET_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "stripe-enterprise-intelligence",
    category: "agent",
    description: "Auto-detected function: stripe-enterprise-intelligence",
    requiredSecrets: ["STRIPE_SECRET_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","GEMINI_API_KEY","GOOGLE_API_KEY"],
    isUsedInApp: false
  },
  {
    name: "stripe-error-handler",
    category: "integration",
    description: "Auto-detected function: stripe-error-handler",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","STRIPE_SECRET_KEY"],
    isUsedInApp: false
  },
  {
    name: "stripe-forensics",
    category: "integration",
    description: "Auto-detected function: stripe-forensics",
    requiredSecrets: ["STRIPE_SECRET_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","AUTHORIZED_IP_ADDRESSES","LOVABLE_API_KEY"],
    isUsedInApp: true
  },
  {
    name: "stripe-history",
    category: "integration",
    description: "Auto-detected function: stripe-history",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","STRIPE_SECRET_KEY"],
    isUsedInApp: false
  },
  {
    name: "stripe-issuing",
    category: "integration",
    description: "Auto-detected function: stripe-issuing",
    requiredSecrets: ["STRIPE_SECRET_KEY"],
    isUsedInApp: false
  },
  {
    name: "stripe-issuing-tokens",
    category: "integration",
    description: "Auto-detected function: stripe-issuing-tokens",
    requiredSecrets: ["STRIPE_SECRET_KEY"],
    isUsedInApp: false
  },
  {
    name: "stripe-payout-controls",
    category: "integration",
    description: "Auto-detected function: stripe-payout-controls",
    requiredSecrets: ["STRIPE_SECRET_KEY"],
    isUsedInApp: true
  },
  {
    name: "stripe-payouts-ai",
    category: "integration",
    description: "Auto-detected function: stripe-payouts-ai",
    requiredSecrets: ["STRIPE_SECRET_KEY","GEMINI_API_KEY","GOOGLE_API_KEY","LOVABLE_API_KEY","LANGSMITH_API_KEY"],
    isUsedInApp: true
  },
  {
    name: "stripe-treasury",
    category: "integration",
    description: "Auto-detected function: stripe-treasury",
    requiredSecrets: ["STRIPE_SECRET_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "stripe-webhook",
    category: "webhook",
    description: "Auto-detected function: stripe-webhook",
    requiredSecrets: ["STRIPE_SECRET_KEY","STRIPE_WEBHOOK_SECRET","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "super-agent-orchestrator",
    category: "agent",
    description: "Auto-detected function: super-agent-orchestrator",
    requiredSecrets: ["LANGSMITH_API_KEY","HUBSPOT_API_KEY","STRIPE_SECRET_KEY","GEMINI_API_KEY","GOOGLE_API_KEY","ANTHROPIC_API_KEY","CALLGEAR_API_KEY","CALLGEAR_API_URL","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "sync-excel-data",
    category: "utility",
    description: "Auto-detected function: sync-excel-data",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "sync-hubspot-data",
    category: "integration",
    description: "Auto-detected function: sync-hubspot-data",
    requiredSecrets: ["HUBSPOT_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "sync-hubspot-leads",
    category: "integration",
    description: "Auto-detected function: sync-hubspot-leads",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY","HUBSPOT_ACCESS_TOKEN"],
    isUsedInApp: false
  },
  {
    name: "sync-hubspot-to-capi",
    category: "integration",
    description: "Auto-detected function: sync-hubspot-to-capi",
    requiredSecrets: ["HUBSPOT_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "sync-hubspot-to-supabase",
    category: "integration",
    description: "Auto-detected function: sync-hubspot-to-supabase",
    requiredSecrets: ["HUBSPOT_API_KEY","SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: true
  },
  {
    name: "system-health-check",
    category: "core",
    description: "Auto-detected function: system-health-check",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_ANON_KEY","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "ultimate-fix",
    category: "utility",
    description: "Auto-detected function: ultimate-fix",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "ultimate-truth-alignment",
    category: "utility",
    description: "Auto-detected function: ultimate-truth-alignment",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
  {
    name: "verify-all-keys",
    category: "utility",
    description: "Auto-detected function: verify-all-keys",
    requiredSecrets: ["SUPABASE_URL","SUPABASE_SERVICE_ROLE_KEY"],
    isUsedInApp: false
  },
];
