import fs from "fs";
import path from "path";

const INVENTORY_PATH = path.resolve("function_inventory.json");
const OUTPUT_PATH = path.resolve("src/config/edgeFunctions.ts");

interface FunctionInventoryItem {
  name: string;
  hasEnvVars: boolean;
  envVarsDetected: string[];
  usedInSrc: boolean;
  usageCount: number;
}

if (!fs.existsSync(INVENTORY_PATH)) {
  console.error(
    "❌ Inventory file not found. Run inventory_functions.ts first.",
  );
  process.exit(1);
}

const inventory: FunctionInventoryItem[] = JSON.parse(
  fs.readFileSync(INVENTORY_PATH, "utf8"),
);

const fileContent = `
/**
 * AUTO-GENERATED CONFIG - DO NOT EDIT MANUALLY
 * Generated by scripts/generate_functions_config.ts
 * 
 * This file lists all available Supabase Edge Functions detected in the codebase.
 * It is used by the Master Control Panel to generate the UI.
 */

export interface EdgeFunctionConfig {
  name: string;
  category: 'core' | 'agent' | 'integration' | 'utility' | 'webhook';
  description: string;
  requiredSecrets: string[];
  isUsedInApp: boolean;
}

export const SUPABASE_EDGE_FUNCTIONS: EdgeFunctionConfig[] = [
${inventory
  .map((item) => {
    let category = "utility";
    if (
      item.name.includes("agent") ||
      item.name.includes("ai-") ||
      item.name.includes("intelligence")
    )
      category = "agent";
    else if (item.name.includes("webhook")) category = "webhook";
    else if (
      item.name.includes("stripe") ||
      item.name.includes("hubspot") ||
      item.name.includes("meta") ||
      item.name.includes("callgear")
    )
      category = "integration";
    else if (
      item.name === "system-health-check" ||
      item.name === "data-quality"
    )
      category = "core";

    return `  {
    name: "${item.name}",
    category: "${category}",
    description: "Auto-detected function: ${item.name}",
    requiredSecrets: ${JSON.stringify(item.envVarsDetected)},
    isUsedInApp: ${item.usedInSrc}
  },`;
  })
  .join("\n")}
];
`;

fs.writeFileSync(OUTPUT_PATH, fileContent);
console.log(
  `✅ Generated config for ${inventory.length} functions at ${OUTPUT_PATH}`,
);
