import { readdir, readFile } from "fs/promises";
import { join } from "path";

const FUNCTIONS_DIR = "supabase/functions";

async function inventory() {
  console.log("🔍 Scanning Supabase Edge Functions...\n");

  try {
    const functions = await readdir(FUNCTIONS_DIR);
    const results = [];

    for (const funcName of functions) {
      if (funcName.startsWith(".") || funcName === "_shared") continue;

      const funcPath = join(FUNCTIONS_DIR, funcName);
      const files = await readdir(funcPath).catch(() => []);

      let indexContent = "";
      try {
        indexContent = await readFile(join(funcPath, "index.ts"), "utf-8");
      } catch (e) {
        // No index.ts
      }

      // Basic heuristic analysis
      const hasSecrets = indexContent.includes("Deno.env.get");
      const isScheduled = indexContent.includes("schedule");
      const hasCors = indexContent.includes("corsHeaders");

      results.push({
        name: funcName,
        hasIndex: files.includes("index.ts"),
        hasSecrets,
        isScheduled,
        hasCors,
      });
    }

    // console.table(results);

    const fileContent = `// Auto-generated by scripts/inventory_functions.ts
export interface EdgeFunction {
  name: string;
  hasIndex: boolean;
  hasSecrets: boolean;
  isScheduled: boolean;
  hasCors: boolean;
}

export const ALL_EDGE_FUNCTIONS: EdgeFunction[] = ${JSON.stringify(results, null, 2)};

export const EDGE_FUNCTION_COUNT = ${results.length};
`;

    const outputPath = join("src", "config", "edgeFunctions.ts");
    await import("fs/promises").then((fs) =>
      fs.writeFile(outputPath, fileContent),
    );
    console.log(
      `✅ Generated config at ${outputPath} with ${results.length} functions.`,
    );
  } catch (error) {
    console.error("Error inventorying functions:", error);
  }
}

inventory();
