#!/bin/bash

# Load .env.local
if [ -f .env.local ]; then
  export $(grep -v '^#' .env.local | xargs)
fi

echo "Syncing secrets to Supabase..."
supabase secrets set \
  STRIPE_SECRET_KEY="$STRIPE_SECRET_KEY" \
  STRIPE_WEBHOOK_SECRET="$STRIPE_WEBHOOK_SECRET" \
  ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  OPENAI_API_KEY="$OPENAI_API_KEY" \
  AGENT_API_KEY="$AGENT_API_KEY" \
  LANGSMITH_API_KEY="$LANGSMITH_API_KEY" \
  HUBSPOT_API_KEY="$HUBSPOT_API_KEY" \
  HUBSPOT_API_KEY="$HUBSPOT_API_KEY" \
  HUBSPOT_ACCESS_TOKEN="$HUBSPOT_ACCESS_TOKEN" \
  GEMINI_API_KEY="$GEMINI_API_KEY" \
  GOOGLE_API_KEY="$GOOGLE_API_KEY" \
  GOOGLE_GEMINI_API_KEY="$GOOGLE_GEMINI_API_KEY" \
  LOVABLE_API_KEY="$LOVABLE_API_KEY" \
  GITHUB_TOKEN="$GITHUB_TOKEN" \
  GITHUB_REPO="$GITHUB_REPO" \
  GITHUB_OWNER="$GITHUB_OWNER" \
  CALLGEAR_API_KEY="$CALLGEAR_API_KEY" \
  CALLGEAR_API_URL="$CALLGEAR_API_URL" \
  STAPE_CAPIG_API_KEY="$STAPE_CAPIG_API_KEY" \
  META_ACCESS_TOKEN="$META_ACCESS_TOKEN" \
  FACEBOOK_ACCESS_TOKEN="$FACEBOOK_ACCESS_TOKEN" \
  FB_ACCESS_TOKEN="$FB_ACCESS_TOKEN" \
  FB_AD_ACCOUNT_ID="$FB_AD_ACCOUNT_ID" \
  LANGCHAIN_PROJECT="$LANGCHAIN_PROJECT" \
  AUTHORIZED_IP_ADDRESSES="$AUTHORIZED_IP_ADDRESSES" \
  FAILSAFE_ROUTING_PHONES="$FAILSAFE_ROUTING_PHONES" \
  VIP_NUMBERS="$VIP_NUMBERS" \
  BLACKLISTED_NUMBERS="$BLACKLISTED_NUMBERS" \
  VIP_ROUTING_PHONES="$VIP_ROUTING_PHONES" \
  DEFAULT_ROUTING_PHONES="$DEFAULT_ROUTING_PHONES" \
  SALES_PHONES="$SALES_PHONES" \
  SUPPORT_PHONES="$SUPPORT_PHONES" \
  BILLING_PHONES="$BILLING_PHONES" \
  OPERATOR_PHONES="$OPERATOR_PHONES" \
  --project-ref ztjndilxurtsfqdsvfds

echo "Secrets synced!"
