-- Atlas Actions: Actionable recommendations generated by the Atlas AI agent
-- These are structured tasks extracted from Atlas analysis (deals, contacts, pipeline health)

CREATE TABLE IF NOT EXISTS public.atlas_actions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  action_type text NOT NULL, -- 'call_lead', 'move_deal', 'follow_up', 'escalate', 'review'
  title text NOT NULL,
  description text,
  priority integer DEFAULT 5 CHECK (priority BETWEEN 1 AND 10), -- 1=low, 10=critical
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'dismissed')),
  contact_id uuid REFERENCES contacts(id),
  deal_id uuid REFERENCES deals(id),
  assigned_to text, -- setter/coach name
  due_date timestamptz,
  metadata jsonb DEFAULT '{}',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  completed_at timestamptz
);

ALTER TABLE public.atlas_actions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_read_atlas_actions" ON public.atlas_actions FOR SELECT TO anon USING (true);
CREATE POLICY "service_role_all_atlas_actions" ON public.atlas_actions FOR ALL TO service_role USING (true);

CREATE INDEX idx_atlas_actions_status ON public.atlas_actions(status) WHERE status = 'pending';
CREATE INDEX idx_atlas_actions_priority ON public.atlas_actions(priority DESC) WHERE status = 'pending';
CREATE INDEX idx_atlas_actions_created ON public.atlas_actions(created_at DESC);
