-- ==============================================================================
-- PHASE 2.5 SCHEMA: COACH PERFORMANCE OS
-- Purpose: Support AI Recommendations, Ghost Session Detection, and Efficiency Logs
-- ==============================================================================

-- 1. Coach Recommendations Table
-- Stores actionable advice generated by the AI engine
CREATE TABLE IF NOT EXISTS public.coach_recommendations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    coach_id TEXT NOT NULL, -- references coach_name or device_id
    type TEXT NOT NULL CHECK (type IN ('ROUTE_OPTIMIZATION', 'GHOST_SESSION', 'FUEL_WASTE', 'HUBSPOT_SYNC')),
    severity TEXT NOT NULL CHECK (severity IN ('HIGH', 'MEDIUM', 'LOW')),
    title TEXT NOT NULL,
    description TEXT,
    action_payload JSONB DEFAULT '{}'::jsonb, -- detailed data (e.g., optimized route array)
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACCEPTED', 'DISMISSED', 'RESOLVED')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,
    resolved_by TEXT
);

-- 2. Route Efficiency Logs
-- Tracks daily efficiency metrics per coach
CREATE TABLE IF NOT EXISTS public.route_efficiency_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    coach_id TEXT NOT NULL,
    log_date DATE NOT NULL DEFAULT CURRENT_DATE,
    total_km_actual NUMERIC,
    total_km_optimal NUMERIC,
    efficiency_score NUMERIC, -- (Optimal / Actual) * 100
    wasted_km NUMERIC GENERATED ALWAYS AS (total_km_actual - total_km_optimal) STORED,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(coach_id, log_date)
);

-- 3. RLS Policies
ALTER TABLE public.coach_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.route_efficiency_logs ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users (dashboard admins) to read/write
CREATE POLICY "Enable read access for authenticated users" ON public.coach_recommendations FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable write access for authenticated users" ON public.coach_recommendations FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update access for authenticated users" ON public.coach_recommendations FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Enable read access for authenticated users" ON public.route_efficiency_logs FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable write access for authenticated users" ON public.route_efficiency_logs FOR INSERT TO authenticated WITH CHECK (true);

-- 4. Grant Access
GRANT ALL ON public.coach_recommendations TO service_role;
GRANT ALL ON public.coach_recommendations TO authenticated;
GRANT ALL ON public.route_efficiency_logs TO service_role;
GRANT ALL ON public.route_efficiency_logs TO authenticated;

-- Refresh schema cache
NOTIFY pgrst, 'reload schema';
