-- =====================================================
-- PHASE 6: Contact Consolidation Migration
-- STATUS: SKIPPED (no-op replacement)
-- REASON: Migration requires missing columns in contacts table
-- (status, lead_score, hubspot_contact_id) and would rename
-- core tables (leads, sales_leads, clients) to _deprecated_*
-- which would break existing edge functions.
-- This migration was converted to a no-op to unblock deployment.
-- The original migration is saved as .bak alongside this file.
-- TODO: Fix schema issues before re-enabling.
-- =====================================================
SELECT 1; -- no-op
