
-- Migration: Create whatsapp_interactions table
create table if not exists public.whatsapp_interactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  phone_number text not null,
  message_text text,
  response_text text,
  status text default 'delivered'::text
);

-- Add RLS policies (optional but recommended)
alter table public.whatsapp_interactions enable row level security;

create policy "Allow insert for service role"
  on public.whatsapp_interactions
  for insert
  to service_role
  with check (true);

create policy "Allow select for service role"
  on public.whatsapp_interactions
  for select
  to service_role
  using (true);
